apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 250-turbonomic-multicloud
  labels:
    type: software
    code: '250'
  annotations:
    displayName: Turbonomic on OpenShift for Multi Cloud
    description: >-
      GitOps deployment of Turbonomic on Multi Cloud environments AWS, Azure and
      IBM Cloud
    deployment-type/gitops: 'true'
spec:
  modules:
    - name: gitops-namespace
      alias: turbo_namespace
      version: v1.11.2
      default: true
      variables:
        - name: name
          value: turbonomic
    - name: gitops-ocp-turbonomic
      alias: gitops-ocp-turbonomic
      version: v2.1.5
    - name: gitops-repo
      alias: gitops_repo
      version: v1.21.0
  variables:
    - name: gitops-ocp-turbonomic_storage_class_name
      type: string
      description: >-
        Name of the block storage class to use - if multizone deployment then
        waitforfirstconsumer must be set on storageclass binding mode
    - name: gitops_repo_host
      type: string
      description: >-
        The host for the git repository. The git host used can be a GitHub,
        GitHub Enterprise, Gitlab, Bitbucket, Gitea or Azure DevOps server. If
        the host is null assumes in-cluster Gitea instance will be used.
      defaultValue: ''
    - name: gitops_repo_org
      type: string
      description: >-
        The org/group where the git repository exists/will be provisioned. If
        the value is left blank then the username org will be used.
      defaultValue: ''
    - name: gitops_repo_project
      type: string
      description: >-
        The project that will be used for the git repo. (Primarily used for
        Azure DevOps repos)
      defaultValue: ''
    - name: gitops_repo_username
      type: string
      description: The username of the user with access to the repository
      defaultValue: ''
    - name: gitops_repo_token
      type: string
      description: The personal access token used to access the repository
      defaultValue: ''
      sensitive: true
    - name: gitops_repo_repo
      type: string
      description: >-
        The short name of the repository (i.e. the part after the org/group
        name)
